### ISSUE TITLE
Handle file paths that are not valid UTF-8

### ISSUE THREAD

**Issue by portstrom** [xi-editor/xi-editor#796] opened 2018-09-14 08:08 UTC
Rust makes a careful distinction between `str` and `OsStr` in order to allow handling strings that are permitted by the operating system but are not valid UTF-8. Paths are based on `OsStr`. Xi naively takes a [`String` for the `new_view` command](https://github.com/google/xi-editor/blob/f751f2f43f2d2220b917a925d93453874b5fb3ca/rust/core-lib/src/rpc.rs#L248). Anyone making a frontend will have to handle paths that are potentially not valid UTF-8, and then figure out how to fit the square peg in a round hole when invoking the `new_view` command. What's the correct way for frontends to deal with this?

**Comment by raphlinus** [comment] 2018-09-14 13:45
I've thought about this. The problem is that non-UTF-8 strings are a bear to encode in JSON. It can be done, say using base64, but then it's a very platform specific encoding.

How much of a problem is this in practice? It seems to me reasonable to say xi can't be used to edit files with such malformed names. I imagine a whole lot of other programming tools will also fail.

**Comment by cmyr** [comment] 2018-09-16 00:59
I could go either way. I'm not familiar enough with windows to know how much of a problem this will be in real use; but I don't think it would be too hard to allow the `new_view` rpc to optionally take a `path_base64` argument, and there's definitely no reason for paths to ever be passed as `String`s.

**Comment by euclio** [comment] 2018-11-07 20:55
Relevant: https://github.com/serde-rs/json/issues/465

**Closed** 2020-03-07 14:08 UTC
Labels: enhancement, refactor
